# Generated by Django 4.0.6 on 2023-06-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catrgory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='category_name',
            new_name='category',
        ),
    ]
