# Generated by Django 4.1.7 on 2023-06-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_rename_creaed_at_vendor_created_at'),
        ('menu', '0002_alter_catrgory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catrgory',
            new_name='Category',
        ),
    ]
